language: java
jdk:
- openjdk8

branches:
  only:
  - master

cache:
  directories:
  - '$HOME/.m2/repository'

before_install:
- chmod +x mvnw

script:
- ./mvnw clean package

notifications:
  email:
    recipients:
    - hsh8220@gmail.com

before_deploy:
- zip -r springboot-reserve *
- mkdir -p deploy
- mv springboot-reserve.zip deploy/springboot-reserve.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: springboot-reserve-deploy
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  local_dir: deploy
  wait-until-deployed: true
  on:
    repo: hsh8220/reserve
    branch: master

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: springboot-reserve-deploy
  key: springboot-reserve.zip
  bundle_type: zip
  application: springboot-reserve
  deployment_group: springboot-reserve-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    repo: hsh8220/reserve
    branch: master