language: java
jdk:
- openjdk8

branches:
  only:
  - master

# Travis CI 서버의 Home
cache:
  directories:
  - '$HOME/.m2/repository'

script: "./mvnw package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
    - hsh8220@gmail.com