spring:
  profiles:
    active: local

# local 환경
---
spring:
  profiles: local
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082